//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerClub", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class CustomerClub : object
    {
        
        private string AddressField;
        
        private string AddressCityField;
        
        private string BankAccountNumberField;
        
        private string BankBranchNameField;
        
        private System.Nullable<long> BankIdField;
        
        private string BankNameField;
        
        private string BirthCertificateCityField;
        
        private System.DateTime BirthDateField;
        
        private string BourseCodeField;
        
        private string BrokerBranchField;
        
        private long BrokerBranchIdField;
        
        private string DetailLedgerCodeField;
        
        private string EmailField;
        
        private string FatherNameField;
        
        private string FirstNameField;
        
        private bool HasDocumentField;
        
        private string IDNumberField;
        
        private string IDSerialField;
        
        private bool IsInCreditContractTradingField;
        
        private bool IsInOfflineTradingField;
        
        private bool IsInOnlineTradingField;
        
        private string LastNameField;
        
        private string MobileField;
        
        private System.DateTime ModifiedDateField;
        
        private string NationalCodeField;
        
        private string PAMCodeField;
        
        private string PhoneField;
        
        private string PostalCodeField;
        
        private string RefererField;
        
        private System.DateTime RegisterDateField;
        
        private bool SexField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCity
        {
            get
            {
                return this.AddressCityField;
            }
            set
            {
                this.AddressCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankAccountNumber
        {
            get
            {
                return this.BankAccountNumberField;
            }
            set
            {
                this.BankAccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankBranchName
        {
            get
            {
                return this.BankBranchNameField;
            }
            set
            {
                this.BankBranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BankId
        {
            get
            {
                return this.BankIdField;
            }
            set
            {
                this.BankIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankName
        {
            get
            {
                return this.BankNameField;
            }
            set
            {
                this.BankNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthCertificateCity
        {
            get
            {
                return this.BirthCertificateCityField;
            }
            set
            {
                this.BirthCertificateCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BourseCode
        {
            get
            {
                return this.BourseCodeField;
            }
            set
            {
                this.BourseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrokerBranch
        {
            get
            {
                return this.BrokerBranchField;
            }
            set
            {
                this.BrokerBranchField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BrokerBranchId
        {
            get
            {
                return this.BrokerBranchIdField;
            }
            set
            {
                this.BrokerBranchIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailLedgerCode
        {
            get
            {
                return this.DetailLedgerCodeField;
            }
            set
            {
                this.DetailLedgerCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FatherName
        {
            get
            {
                return this.FatherNameField;
            }
            set
            {
                this.FatherNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDocument
        {
            get
            {
                return this.HasDocumentField;
            }
            set
            {
                this.HasDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDNumber
        {
            get
            {
                return this.IDNumberField;
            }
            set
            {
                this.IDNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDSerial
        {
            get
            {
                return this.IDSerialField;
            }
            set
            {
                this.IDSerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInCreditContractTrading
        {
            get
            {
                return this.IsInCreditContractTradingField;
            }
            set
            {
                this.IsInCreditContractTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInOfflineTrading
        {
            get
            {
                return this.IsInOfflineTradingField;
            }
            set
            {
                this.IsInOfflineTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInOnlineTrading
        {
            get
            {
                return this.IsInOnlineTradingField;
            }
            set
            {
                this.IsInOnlineTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile
        {
            get
            {
                return this.MobileField;
            }
            set
            {
                this.MobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAMCode
        {
            get
            {
                return this.PAMCodeField;
            }
            set
            {
                this.PAMCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referer
        {
            get
            {
                return this.RefererField;
            }
            set
            {
                this.RefererField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RegisterDate
        {
            get
            {
                return this.RegisterDateField;
            }
            set
            {
                this.RegisterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Sex
        {
            get
            {
                return this.SexField;
            }
            set
            {
                this.SexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
        "Management")]
    public partial class ExceptionMessage : object
    {
        
        private int ErrorCodeField;
        
        private string MessageField;
        
        private System.Collections.Generic.KeyValuePair<string, ClubService.PropertyValidatorReason>[] PropertyErrorsField;
        
        private string RawMessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, ClubService.PropertyValidatorReason>[] PropertyErrors
        {
            get
            {
                return this.PropertyErrorsField;
            }
            set
            {
                this.PropertyErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawMessage
        {
            get
            {
                return this.RawMessageField;
            }
            set
            {
                this.RawMessageField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyValidatorReason", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.Infrastructure.Entities.Exce" +
        "ptions")]
    public enum PropertyValidatorReason : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidFormat = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidData = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FirmClub", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class FirmClub : object
    {
        
        private string ActivityFieldField;
        
        private string AddressField;
        
        private string AddressCityField;
        
        private string BourseCodeField;
        
        private string EconomicNumberField;
        
        private string EmailField;
        
        private System.DateTime FirmRegisterDateField;
        
        private string FirmRegisterLocationField;
        
        private string FirmRegisterNumberField;
        
        private string FirmTitleField;
        
        private bool HasDocumentField;
        
        private bool IsInCreditContractTradingField;
        
        private bool IsInOfflineTradingField;
        
        private bool IsInOnlineTradingField;
        
        private System.DateTime ModifiedDateField;
        
        private string NationalIdentificationField;
        
        private string PAMCodeField;
        
        private string PostalCodeField;
        
        private string RefererField;
        
        private string TelephoneField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityField
        {
            get
            {
                return this.ActivityFieldField;
            }
            set
            {
                this.ActivityFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressCity
        {
            get
            {
                return this.AddressCityField;
            }
            set
            {
                this.AddressCityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BourseCode
        {
            get
            {
                return this.BourseCodeField;
            }
            set
            {
                this.BourseCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EconomicNumber
        {
            get
            {
                return this.EconomicNumberField;
            }
            set
            {
                this.EconomicNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FirmRegisterDate
        {
            get
            {
                return this.FirmRegisterDateField;
            }
            set
            {
                this.FirmRegisterDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmRegisterLocation
        {
            get
            {
                return this.FirmRegisterLocationField;
            }
            set
            {
                this.FirmRegisterLocationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmRegisterNumber
        {
            get
            {
                return this.FirmRegisterNumberField;
            }
            set
            {
                this.FirmRegisterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmTitle
        {
            get
            {
                return this.FirmTitleField;
            }
            set
            {
                this.FirmTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasDocument
        {
            get
            {
                return this.HasDocumentField;
            }
            set
            {
                this.HasDocumentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInCreditContractTrading
        {
            get
            {
                return this.IsInCreditContractTradingField;
            }
            set
            {
                this.IsInCreditContractTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInOfflineTrading
        {
            get
            {
                return this.IsInOfflineTradingField;
            }
            set
            {
                this.IsInOfflineTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInOnlineTrading
        {
            get
            {
                return this.IsInOnlineTradingField;
            }
            set
            {
                this.IsInOnlineTradingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.ModifiedDateField;
            }
            set
            {
                this.ModifiedDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalIdentification
        {
            get
            {
                return this.NationalIdentificationField;
            }
            set
            {
                this.NationalIdentificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAMCode
        {
            get
            {
                return this.PAMCodeField;
            }
            set
            {
                this.PAMCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostalCode
        {
            get
            {
                return this.PostalCodeField;
            }
            set
            {
                this.PostalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referer
        {
            get
            {
                return this.RefererField;
            }
            set
            {
                this.RefererField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telephone
        {
            get
            {
                return this.TelephoneField;
            }
            set
            {
                this.TelephoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedCollectionTradeDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.Infrastructure.DataAccess")]
    public partial class PagedCollectionTradeDto : object
    {
        
        private ClubService.TradeDto[] ResultField;
        
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClubService.TradeDto[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class TradeDto : object
    {
        
        private decimal AddedValueTaxField;
        
        private decimal BondDividendField;
        
        private long BranchIDField;
        
        private string BranchTitleField;
        
        private decimal DiscountField;
        
        private bool InstrumentCategoryField;
        
        private string MarketInstrumentISINField;
        
        private decimal PriceField;
        
        private decimal TotalCommissionField;
        
        private string TradeCodeField;
        
        private System.DateTime TradeDateField;
        
        private decimal TradeItemBrokerField;
        
        private decimal TradeItemRayanBourseField;
        
        private string TradeNumberField;
        
        private bool TradeStationTypeField;
        
        private string TradeSymbolField;
        
        private ClubService.TradeSideEnumDto TradeTypeField;
        
        private decimal TransferTaxField;
        
        private decimal VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AddedValueTax
        {
            get
            {
                return this.AddedValueTaxField;
            }
            set
            {
                this.AddedValueTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BondDividend
        {
            get
            {
                return this.BondDividendField;
            }
            set
            {
                this.BondDividendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchTitle
        {
            get
            {
                return this.BranchTitleField;
            }
            set
            {
                this.BranchTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InstrumentCategory
        {
            get
            {
                return this.InstrumentCategoryField;
            }
            set
            {
                this.InstrumentCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketInstrumentISIN
        {
            get
            {
                return this.MarketInstrumentISINField;
            }
            set
            {
                this.MarketInstrumentISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalCommission
        {
            get
            {
                return this.TotalCommissionField;
            }
            set
            {
                this.TotalCommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode
        {
            get
            {
                return this.TradeCodeField;
            }
            set
            {
                this.TradeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TradeDate
        {
            get
            {
                return this.TradeDateField;
            }
            set
            {
                this.TradeDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TradeItemBroker
        {
            get
            {
                return this.TradeItemBrokerField;
            }
            set
            {
                this.TradeItemBrokerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TradeItemRayanBourse
        {
            get
            {
                return this.TradeItemRayanBourseField;
            }
            set
            {
                this.TradeItemRayanBourseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeNumber
        {
            get
            {
                return this.TradeNumberField;
            }
            set
            {
                this.TradeNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TradeStationType
        {
            get
            {
                return this.TradeStationTypeField;
            }
            set
            {
                this.TradeStationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeSymbol
        {
            get
            {
                return this.TradeSymbolField;
            }
            set
            {
                this.TradeSymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClubService.TradeSideEnumDto TradeType
        {
            get
            {
                return this.TradeTypeField;
            }
            set
            {
                this.TradeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TransferTax
        {
            get
            {
                return this.TransferTaxField;
            }
            set
            {
                this.TransferTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TradeSideEnumDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public enum TradeSideEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Buy = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sell = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class BranchDto : object
    {
        
        private System.Nullable<ClubService.BranchDestinationType> BranchDestinationTypeField;
        
        private long BranchIDField;
        
        private string BranchNameField;
        
        private string BranchSymbolField;
        
        private string BranchTraderCodeField;
        
        private System.Nullable<long> OfficeIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ClubService.BranchDestinationType> BranchDestinationType
        {
            get
            {
                return this.BranchDestinationTypeField;
            }
            set
            {
                this.BranchDestinationTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName
        {
            get
            {
                return this.BranchNameField;
            }
            set
            {
                this.BranchNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchSymbol
        {
            get
            {
                return this.BranchSymbolField;
            }
            set
            {
                this.BranchSymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchTraderCode
        {
            get
            {
                return this.BranchTraderCodeField;
            }
            set
            {
                this.BranchTraderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BranchDestinationType", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Enums")]
    public enum BranchDestinationType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Namak = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOT = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SymbolDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class SymbolDto : object
    {
        
        private string FirmISINField;
        
        private string ISINField;
        
        private bool InstrumentCategoryField;
        
        private string SymbolField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmISIN
        {
            get
            {
                return this.FirmISINField;
            }
            set
            {
                this.FirmISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISIN
        {
            get
            {
                return this.ISINField;
            }
            set
            {
                this.ISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InstrumentCategory
        {
            get
            {
                return this.InstrumentCategoryField;
            }
            set
            {
                this.InstrumentCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MarketEnumDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public enum MarketEnumDto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TSE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IME = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IEE = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EFP = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemainDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class RemainDto : object
    {
        
        private decimal AdjustedRemainField;
        
        private decimal BlockedRemainField;
        
        private decimal CreditField;
        
        private System.Nullable<System.DateTime> CreditDateField;
        
        private decimal CurrentRemainField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AdjustedRemain
        {
            get
            {
                return this.AdjustedRemainField;
            }
            set
            {
                this.AdjustedRemainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BlockedRemain
        {
            get
            {
                return this.BlockedRemainField;
            }
            set
            {
                this.BlockedRemainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit
        {
            get
            {
                return this.CreditField;
            }
            set
            {
                this.CreditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreditDate
        {
            get
            {
                return this.CreditDateField;
            }
            set
            {
                this.CreditDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrentRemain
        {
            get
            {
                return this.CurrentRemainField;
            }
            set
            {
                this.CurrentRemainField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PortfolioDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service")]
    public partial class PortfolioDto : object
    {
        
        private string ISINField;
        
        private string SymbolField;
        
        private long VolumeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISIN
        {
            get
            {
                return this.ISINField;
            }
            set
            {
                this.ISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedCollectionCustomerClub", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.Infrastructure.DataAccess")]
    public partial class PagedCollectionCustomerClub : object
    {
        
        private ClubService.CustomerClub[] ResultField;
        
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClubService.CustomerClub[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedCollectionFirmClub", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.Infrastructure.DataAccess")]
    public partial class PagedCollectionFirmClub : object
    {
        
        private ClubService.FirmClub[] ResultField;
        
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClubService.FirmClub[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerMomentaryAsset", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service.Customer")]
    public partial class CustomerMomentaryAsset : object
    {
        
        private string CustomerTitleField;
        
        private string ISINField;
        
        private decimal LastPriceField;
        
        private long MarketInstrumentIdField;
        
        private string MarketInstrumentTitleField;
        
        private string SymbolField;
        
        private string TradeCodeField;
        
        private int TradeSystemIdField;
        
        private decimal VolumeField;
        
        private decimal VolumeInPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerTitle
        {
            get
            {
                return this.CustomerTitleField;
            }
            set
            {
                this.CustomerTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISIN
        {
            get
            {
                return this.ISINField;
            }
            set
            {
                this.ISINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal LastPrice
        {
            get
            {
                return this.LastPriceField;
            }
            set
            {
                this.LastPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MarketInstrumentId
        {
            get
            {
                return this.MarketInstrumentIdField;
            }
            set
            {
                this.MarketInstrumentIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketInstrumentTitle
        {
            get
            {
                return this.MarketInstrumentTitleField;
            }
            set
            {
                this.MarketInstrumentTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Symbol
        {
            get
            {
                return this.SymbolField;
            }
            set
            {
                this.SymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TradeCode
        {
            get
            {
                return this.TradeCodeField;
            }
            set
            {
                this.TradeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TradeSystemId
        {
            get
            {
                return this.TradeSystemIdField;
            }
            set
            {
                this.TradeSystemIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Volume
        {
            get
            {
                return this.VolumeField;
            }
            set
            {
                this.VolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VolumeInPrice
        {
            get
            {
                return this.VolumeInPriceField;
            }
            set
            {
                this.VolumeInPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedCollectionTotalBrokerCommissionDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.Infrastructure.DataAccess")]
    public partial class PagedCollectionTotalBrokerCommissionDto : object
    {
        
        private ClubService.TotalBrokerCommissionDto[] ResultField;
        
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClubService.TotalBrokerCommissionDto[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords
        {
            get
            {
                return this.TotalRecordsField;
            }
            set
            {
                this.TotalRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalBrokerCommissionDto", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.External" +
        "Service.Customer")]
    public partial class TotalBrokerCommissionDto : object
    {
        
        private string AccountCodeField;
        
        private System.DateTime DateField;
        
        private decimal NonOnlineBuyCommissionField;
        
        private decimal NonOnlineSellCommissionField;
        
        private decimal OnlineBuyCommissionField;
        
        private decimal OnlineSellCommissionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountCode
        {
            get
            {
                return this.AccountCodeField;
            }
            set
            {
                this.AccountCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NonOnlineBuyCommission
        {
            get
            {
                return this.NonOnlineBuyCommissionField;
            }
            set
            {
                this.NonOnlineBuyCommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal NonOnlineSellCommission
        {
            get
            {
                return this.NonOnlineSellCommissionField;
            }
            set
            {
                this.NonOnlineSellCommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OnlineBuyCommission
        {
            get
            {
                return this.OnlineBuyCommissionField;
            }
            set
            {
                this.OnlineBuyCommissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal OnlineSellCommission
        {
            get
            {
                return this.OnlineSellCommissionField;
            }
            set
            {
                this.OnlineSellCommissionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Office", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
        "Management")]
    public partial class Office : object
    {
        
        private long OfficeIdField;
        
        private string OfficeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OfficeId
        {
            get
            {
                return this.OfficeIdField;
            }
            set
            {
                this.OfficeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeName
        {
            get
            {
                return this.OfficeNameField;
            }
            set
            {
                this.OfficeNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClubService.ICustomerClubExternalService")]
    public interface ICustomerClubExternalService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerByNationalCode", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerByNationalCodeResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerByNationalCodeExceptio" +
            "nMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.CustomerClub> GetCustomerByNationalCodeAsync(string nationalIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetFirmByNationalIdentification", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetFirmByNationalIdentificationRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetFirmByNationalIdentificationEx" +
            "ceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.FirmClub> GetFirmByNationalIdentificationAsync(string nationalIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetTradeTimeTrades", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetTradeTimeTradesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetTradeTimeTradesExceptionMessag" +
            "eFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PagedCollectionTradeDto> GetTradeTimeTradesAsync(System.DateTime fromTime, System.DateTime toTime, int page);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetTradeList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetTradeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetTradeListExceptionMessageFault" +
            "", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.TradeDto[]> GetTradeListAsync(string tradeCode, System.DateTime fromDate, System.DateTime toDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeCodes", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeCodesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeCodesExceptionMessag" +
            "eFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<string[]> GetDailyTradeCodesAsync(System.DateTime tradeDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetDailyTradeListExceptionMessage" +
            "Fault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PagedCollectionTradeDto> GetDailyTradeListAsync(System.DateTime tradeDate, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetBranchList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetBranchListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetBranchListExceptionMessageFaul" +
            "t", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.BranchDto[]> GetBranchListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetTSESymbolList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetTSESymbolListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetTSESymbolListExceptionMessageF" +
            "ault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.SymbolDto[]> GetTSESymbolListAsync(System.DateTime symbolDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemain", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainExceptionMessage" +
            "Fault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainAsync(string nationalIdentification, ClubService.MarketEnumDto market);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerPortfolio", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerPortfolioResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerPortfolioExceptionMess" +
            "ageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PortfolioDto[]> GetCustomerPortfolioAsync(string nationalIdentification);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerListExceptionMessageFa" +
            "ult", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PagedCollectionCustomerClub> GetCustomerListAsync(System.DateTime modifiedDate, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetFirmList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetFirmListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetFirmListExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PagedCollectionFirmClub> GetFirmListAsync(System.DateTime modifiedDate, int pageIndex, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetTenEndCustomerTurnover", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetTenEndCustomerTurnoverResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetTenEndCustomerTurnoverExceptio" +
            "nMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.TradeDto[]> GetTenEndCustomerTurnoverAsync(string tradeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetMarketInstrumentMomentaryPrice" +
            "", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetMarketInstrumentMomentaryPrice" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetMarketInstrumentMomentaryPrice" +
            "ExceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<decimal> GetMarketInstrumentMomentaryPriceAsync(string isin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerMomentaryAssets", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerMomentaryAssetsRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerMomentaryAssetsExcepti" +
            "onMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.CustomerMomentaryAsset[]> GetCustomerMomentaryAssetsAsync(string tradeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerTotalBrokerCommission", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerTotalBrokerCommissionR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerTotalBrokerCommissionE" +
            "xceptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.PagedCollectionTotalBrokerCommissionDto> GetCustomerTotalBrokerCommissionAsync(System.DateTime fromDate, System.DateTime toDate, int page, int pageSize);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetOfficeList", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetOfficeListResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetOfficeListExceptionMessageFaul" +
            "t", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.Office[]> GetOfficeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainWithTradeCode", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainWithTradeCodeRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainWithTradeCodeExc" +
            "eptionMessageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainWithTradeCodeAsync(string tradeCode, ClubService.MarketEnumDto market);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainInDate", ReplyAction="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainInDateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(ClubService.ExceptionMessage), Action="http://tempuri.org/ICustomerClubExternalService/GetCustomerRemainInDateExceptionM" +
            "essageFault", Name="ExceptionMessage", Namespace="http://schemas.datacontract.org/2004/07/TadbirPardaz.TBS.Domain.Entities.Customer" +
            "Management")]
        System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainInDateAsync(string tradeCode, System.DateTime dateOfRemain, ClubService.MarketEnumDto market);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ICustomerClubExternalServiceChannel : ClubService.ICustomerClubExternalService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CustomerClubExternalServiceClient : System.ServiceModel.ClientBase<ClubService.ICustomerClubExternalService>, ClubService.ICustomerClubExternalService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CustomerClubExternalServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CustomerClubExternalServiceClient.GetBindingForEndpoint(endpointConfiguration), CustomerClubExternalServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerClubExternalServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CustomerClubExternalServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerClubExternalServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CustomerClubExternalServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CustomerClubExternalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ClubService.CustomerClub> GetCustomerByNationalCodeAsync(string nationalIdentification)
        {
            return base.Channel.GetCustomerByNationalCodeAsync(nationalIdentification);
        }
        
        public System.Threading.Tasks.Task<ClubService.FirmClub> GetFirmByNationalIdentificationAsync(string nationalIdentification)
        {
            return base.Channel.GetFirmByNationalIdentificationAsync(nationalIdentification);
        }
        
        public System.Threading.Tasks.Task<ClubService.PagedCollectionTradeDto> GetTradeTimeTradesAsync(System.DateTime fromTime, System.DateTime toTime, int page)
        {
            return base.Channel.GetTradeTimeTradesAsync(fromTime, toTime, page);
        }
        
        public System.Threading.Tasks.Task<ClubService.TradeDto[]> GetTradeListAsync(string tradeCode, System.DateTime fromDate, System.DateTime toDate)
        {
            return base.Channel.GetTradeListAsync(tradeCode, fromDate, toDate);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDailyTradeCodesAsync(System.DateTime tradeDate)
        {
            return base.Channel.GetDailyTradeCodesAsync(tradeDate);
        }
        
        public System.Threading.Tasks.Task<ClubService.PagedCollectionTradeDto> GetDailyTradeListAsync(System.DateTime tradeDate, int page, int pageSize)
        {
            return base.Channel.GetDailyTradeListAsync(tradeDate, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ClubService.BranchDto[]> GetBranchListAsync()
        {
            return base.Channel.GetBranchListAsync();
        }
        
        public System.Threading.Tasks.Task<ClubService.SymbolDto[]> GetTSESymbolListAsync(System.DateTime symbolDate)
        {
            return base.Channel.GetTSESymbolListAsync(symbolDate);
        }
        
        public System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainAsync(string nationalIdentification, ClubService.MarketEnumDto market)
        {
            return base.Channel.GetCustomerRemainAsync(nationalIdentification, market);
        }
        
        public System.Threading.Tasks.Task<ClubService.PortfolioDto[]> GetCustomerPortfolioAsync(string nationalIdentification)
        {
            return base.Channel.GetCustomerPortfolioAsync(nationalIdentification);
        }
        
        public System.Threading.Tasks.Task<ClubService.PagedCollectionCustomerClub> GetCustomerListAsync(System.DateTime modifiedDate, int pageIndex, int pageSize)
        {
            return base.Channel.GetCustomerListAsync(modifiedDate, pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<ClubService.PagedCollectionFirmClub> GetFirmListAsync(System.DateTime modifiedDate, int pageIndex, int pageSize)
        {
            return base.Channel.GetFirmListAsync(modifiedDate, pageIndex, pageSize);
        }
        
        public System.Threading.Tasks.Task<ClubService.TradeDto[]> GetTenEndCustomerTurnoverAsync(string tradeCode)
        {
            return base.Channel.GetTenEndCustomerTurnoverAsync(tradeCode);
        }
        
        public System.Threading.Tasks.Task<decimal> GetMarketInstrumentMomentaryPriceAsync(string isin)
        {
            return base.Channel.GetMarketInstrumentMomentaryPriceAsync(isin);
        }
        
        public System.Threading.Tasks.Task<ClubService.CustomerMomentaryAsset[]> GetCustomerMomentaryAssetsAsync(string tradeCode)
        {
            return base.Channel.GetCustomerMomentaryAssetsAsync(tradeCode);
        }
        
        public System.Threading.Tasks.Task<ClubService.PagedCollectionTotalBrokerCommissionDto> GetCustomerTotalBrokerCommissionAsync(System.DateTime fromDate, System.DateTime toDate, int page, int pageSize)
        {
            return base.Channel.GetCustomerTotalBrokerCommissionAsync(fromDate, toDate, page, pageSize);
        }
        
        public System.Threading.Tasks.Task<ClubService.Office[]> GetOfficeListAsync()
        {
            return base.Channel.GetOfficeListAsync();
        }
        
        public System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainWithTradeCodeAsync(string tradeCode, ClubService.MarketEnumDto market)
        {
            return base.Channel.GetCustomerRemainWithTradeCodeAsync(tradeCode, market);
        }
        
        public System.Threading.Tasks.Task<ClubService.RemainDto> GetCustomerRemainInDateAsync(string tradeCode, System.DateTime dateOfRemain, ClubService.MarketEnumDto market)
        {
            return base.Channel.GetCustomerRemainInDateAsync(tradeCode, dateOfRemain, market);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerClubExternalService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerClubExternalService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerClubExternalService))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.100.20:2020/TadbirPardaz.CustomerClubExternalService");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICustomerClubExternalService1))
            {
                return new System.ServiceModel.EndpointAddress("https://tbs.armanbroker.ir/TadbirPardaz.CustomerClubExternalService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICustomerClubExternalService,
            
            BasicHttpBinding_ICustomerClubExternalService1,
        }
    }
}
